### ISSUE TITLE
IsgdShortener.shorten not ran asynchronously

### ISSUE THREAD

**Issue by loidsemus** [NiklasEi/LMGTFY#2]
Not really an issue but more of a reminder; when you implement link shortening, remember to shorten it asynchronously, or it will freeze the main thread

Too lazy to do it myself so I'll just open an issue about it 😄

**Comment by NiklasEi** [comment]
I know, that was a test with a shortener in general. The problem is, that they do not support parameters. If I send an url containing a query, is.gd just returns an error. I will probably not implement an external shortener.

I thought about adding a system that creates keys and maps them with the long links. Then just send those keys as links and add a click event with the matching "real" link. Just for the thrill of it ^^

**Comment by loidsemus** [comment]
Huh? It works perfectly, [here's an example I just made real quick](https://github.com/Meepidy/LMGTFY-T) and it works like a charm (even including some of your code)
use /lmgtfy [query] or /lmgtfy -d [query] to skip lmgtfy.com and go directly to google

and as a bonus it does it async, but I am abusing static a bit I'll give you that

**Comment by NiklasEi** [comment]
Works for me with queries only having one word, yes. I always tried with more then one and then it doesn't work anymore (also not in your plugin).

I will look into this later, would be nice to get that running.

Edit:
This works: https://is.gd/create.php?format=simple&url=https://lmgtfy.com/?q=testingagain
While this doesn't work: https://is.gd/create.php?format=simple&url=https://lmgtfy.com/?q=testingagain+secondword

**Comment by loidsemus** [comment]
Oh, didn't notice that, I thought that was caused by api request limitations or something, but now I do 😄 
I don't think this is fixable on our end, I think is.gd need to fix it themselves

**Comment by NiklasEi** [comment]
Nvm, I just fixed it :)

This works: https://is.gd/create.php?format=simple&url=https://lmgtfy.com/?q=testingagain%2Bsecondword

I will implement this asap.

**Comment by loidsemus** [comment]
Nevermind from me too 😛

**Comment by loidsemus** [comment]
Quick fix on that: see my pull request and replace " " with "+" in my String.join

**Comment by loidsemus** [comment]
no wait wtf am i saying lol sorry i mean %2B

**Comment by loidsemus** [comment]
Uh nevermind, now it works for me with just pluses

Edit: due to the URLEncoder.encode
